### ISSUE TITLE
Base64enc and Base64dec crash

### ISSUE THREAD

**Issue by GeigerCounter** [NicolaiSoeborg/manipulator-plugin#1]
If I try to decode Base64 containing NUL characters `\0` , micro crashes.

**Comment by NicolaiSoeborg** [comment]
Do you have an example?

If I decode `dGVzdABpbmc=` it correctly decodes to `test\0ing` 😃

**Comment by GeigerCounter** [comment]
Oh huh. Maybe it's something else is going on. I am using a nightly build.

**Comment by NicolaiSoeborg** [comment]
I'm closing this for now.

Please reopen if you can find a reproducible example.
