### ISSUE TITLE
wrap in braces & capital case

### ISSUE THREAD

**Issue by marinopposite** [NicolaiSoeborg/manipulator-plugin#2]
I wrote some small enhancements to your _manipulator.lua_:

Command: **capital**   (uppercases the first letter of marked block or letter at cursor when nothing is marked)

```
function capital() manipulate("[%a]", string.upper, 1) end
MakeCommand("capital", "manipulator.capital")
```

As per resolving issue #707 in micro, these wrap the marked text either in braces, curly braces or square brackets:

Command: **curly**, **brace**, **square**

```
function curly()   manipulate(".*", "{%1}", 1) end
MakeCommand("curly", "manipulator.curly")

function brace()   manipulate(".*", "(%1)", 1) end
MakeCommand("brace", "manipulator.brace")

function square()  manipulate(".*", "[%1]", 1) end
MakeCommand("square", "manipulator.square")

```

To accomodate this I needed to change the declaration of the function _manipulate_ at line _44_ by adding the argument _num_:

`function manipulate(regex, manipulator, num)`

 and line _49_ in _it_:

`
    local newTxt = string.gsub(oldTxt, regex, manipulator, num)
`

to control the number of replacements (effectively to restrict them to _only_ one).

I apologize for not going through entire pull/push routine due to this being so small.

Best regards.

**Comment by marinopposite** [comment]
```
function quote()   manipulate(".*", '"%1"', 1) end
MakeCommand("quote", "manipulator.quote" )

function single()  manipulate(".*", "'%1'", 1) end
MakeCommand("single", "manipulator.single")

function generic() manipulate(".*", "<%1>", 1) end
MakeCommand("generic", "manipulator.generic")
```

**Comment by NicolaiSoeborg** [comment]
Hi @marinopposite 

Thanks for the contribution!
It has been added now and I will make a PR to get it upstream in micro's repo.
