### ISSUE TITLE
Command ‘capital’ only capitalises the first word in selected text of several words

### ISSUE THREAD

**Issue by wiremoons** [NicolaiSoeborg/manipulator-plugin#3]
The readme on the GitHib repo states:

> If you have a selection, the plugin will change all of the selection.

However, if I select a sentence, then use `Ctrl + E` and enter: `capital` the sentence gets altered, but only the first word of the selected text get capitalised. I was expecting all selected text to have each of the words capitalised?

Is this a bug, and can it be fixed? Or should I being creating capitalised words in a selected string of text in a different way?

Thanks for your help, and the plugin!

Simon

**Comment by NicolaiSoeborg** [comment]
This is indeed a bug, thanks for reporting it :smile: 

Fixed in v1.3.2
