### ISSUE TITLE
key bindings not working, or i am doing it wrong ?

### ISSUE THREAD

**Issue by bokunodev** [NicolaiSoeborg/manipulator-plugin#5]
``
Error: manipulator.dquote does not exist

Press enter to continue
Error: manipulator.squote does not exist

Press enter to continue
Error: manipulator.brace does not exist

Press enter to continue
Error: manipulator.curly does not exist

Press enter to continue
Error: manipulator.square does not exist

Press enter to continue
Error: manipulator.angle does not exist

Press enter to continue
``

**Comment by gj1118** [comment]
I am facing the same issue. Can you please confirm how you were able to resolve it ?  I can confirm that I am seeing `manipulator` in the plugin list command. Please confirm  

Thanks

**Comment by bokunodev** [comment]
@gj1118 
maybe the plugin break due to micro API change.
instead of ``manipulator.blabla....``
you can use ``command-edit:brace``, ``command-edit:upper`` etc.
its not elegant solution but it works.
